/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nq;

import java.util.Vector;
import java.util.stream.IntStream;

public class App {
    public static void main(String[] args) {
    	
    	int size = Integer.valueOf(args[0]);    	
    	Vector<Integer> v = new Vector<Integer>();
    	IntStream.range(0, size).forEachOrdered(i -> {
    		v.add(i);
    	});
    	
    	Solution s = new Solution(v);
    	
    	s.show();
    }
}
